2021/01/27 17:25:46 : Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 665, in storage_data
    getattr(self.get_source_cart(), 'finish_storage_data')()
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/basecart.py", line 4043, in finish_storage_data
    folder_upload = self.get_folder_upload(self._migration_id)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/basecart.py", line 4055, in get_folder_upload
    folder_upload = root_path + '/' + DIR_UPLOAD + '/' + get_config_ini('src', 'file', file='test.ini')
TypeError: can only concatenate str (not "NoneType") to str

2021/01/27 17:25:48 : categories_errors 2: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 1733, in after_category_import
    'thumbnail_id': thumbnail_id['data'][0]['ID'] if len(thumbnail_id['data']) > 0 else None
NameError: name 'thumbnail_id' is not defined

2021/01/27 17:25:48 : categories_errors 3: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 1733, in after_category_import
    'thumbnail_id': thumbnail_id['data'][0]['ID'] if len(thumbnail_id['data']) > 0 else None
NameError: name 'thumbnail_id' is not defined

2021/01/27 17:25:48 : categories_errors 4: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 1733, in after_category_import
    'thumbnail_id': thumbnail_id['data'][0]['ID'] if len(thumbnail_id['data']) > 0 else None
NameError: name 'thumbnail_id' is not defined

2021/01/27 17:25:48 : categories_errors 5: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 1733, in after_category_import
    'thumbnail_id': thumbnail_id['data'][0]['ID'] if len(thumbnail_id['data']) > 0 else None
NameError: name 'thumbnail_id' is not defined

2021/01/27 17:25:48 : categories_errors 6: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 1733, in after_category_import
    'thumbnail_id': thumbnail_id['data'][0]['ID'] if len(thumbnail_id['data']) > 0 else None
NameError: name 'thumbnail_id' is not defined

2021/01/27 17:25:48 : categories_errors 7: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 1733, in after_category_import
    'thumbnail_id': thumbnail_id['data'][0]['ID'] if len(thumbnail_id['data']) > 0 else None
NameError: name 'thumbnail_id' is not defined

2021/01/27 17:26:00 : orders_errors 1: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 2: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 3: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 4: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 5: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 6: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 7: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 8: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

