2021/01/27 17:26:00 : orders_errors 1: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 2: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 3: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 4: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 5: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 6: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 7: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

2021/01/27 17:26:00 : orders_errors 8: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 742, in convert_order_export
    order_data['items'] = order_items
NameError: name 'order_items' is not defined

