2021/01/21 16:48:58 : categories_errors 2: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:00 : categories_errors 3: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:01 : categories_errors 4: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:01 : categories_errors 5: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:02 : categories_errors 6: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:02 : categories_errors 7: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:03 : categories_errors 8: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 296, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 1175, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:04 : categories_errors 9: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:06 : categories_errors 10: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:06 : categories_errors 11: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:07 : categories_errors 12: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:08 : categories_errors 13: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 296, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 1175, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:36 : categories_errors 14: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 296, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 1175, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:38 : categories_errors 15: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:38 : categories_errors 16: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:40 : categories_errors 17: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 296, in convert_category_export
    parent_data = self.get_category_parent(category['parent_id'])
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 1175, in get_category_parent
    category_convert = self.convert_category_export(category, categories_ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:41 : categories_errors 19: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:41 : categories_errors 20: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:42 : categories_errors 22: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

2021/01/21 16:49:43 : categories_errors 23: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 299, in convert_category_export
    category_data['id'] = category['id']
KeyError: 'id'

