2021/01/25 17:36:55 : categories_errors 8: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 2102, in category_import
    'thumbnail_id': thumbnail_id['data'][0]['ID']
IndexError: list index out of range

2021/01/25 17:36:55 : categories_errors 13: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 2102, in category_import
    'thumbnail_id': thumbnail_id['data'][0]['ID']
IndexError: list index out of range

2021/01/25 17:36:55 : categories_errors 14: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 2102, in category_import
    'thumbnail_id': thumbnail_id['data'][0]['ID']
IndexError: list index out of range

2021/01/25 17:36:56 : categories_errors 17: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1072, in migration
    import_data = fn_import(convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 2102, in category_import
    'thumbnail_id': thumbnail_id['data'][0]['ID']
IndexError: list index out of range

