2021/01/27 18:07:04 : orders_errors 1: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 4251, in after_order_import
    order_customer_id = self.get_map_field_by_src(self.TYPE_CUSTOMER, customer['id'])
KeyError: 'id'

2021/01/27 18:07:04 : orders_errors 2: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 4251, in after_order_import
    order_customer_id = self.get_map_field_by_src(self.TYPE_CUSTOMER, customer['id'])
KeyError: 'id'

2021/01/27 18:07:04 : orders_errors 3: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 4251, in after_order_import
    order_customer_id = self.get_map_field_by_src(self.TYPE_CUSTOMER, customer['id'])
KeyError: 'id'

2021/01/27 18:07:04 : orders_errors 4: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 4251, in after_order_import
    order_customer_id = self.get_map_field_by_src(self.TYPE_CUSTOMER, customer['id'])
KeyError: 'id'

2021/01/27 18:07:04 : orders_errors 5: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 4251, in after_order_import
    order_customer_id = self.get_map_field_by_src(self.TYPE_CUSTOMER, customer['id'])
KeyError: 'id'

2021/01/27 18:07:04 : orders_errors 6: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 4251, in after_order_import
    order_customer_id = self.get_map_field_by_src(self.TYPE_CUSTOMER, customer['id'])
KeyError: 'id'

2021/01/27 18:07:04 : orders_errors 7: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 4251, in after_order_import
    order_customer_id = self.get_map_field_by_src(self.TYPE_CUSTOMER, customer['id'])
KeyError: 'id'

2021/01/27 18:07:04 : orders_errors 8: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 4251, in after_order_import
    order_customer_id = self.get_map_field_by_src(self.TYPE_CUSTOMER, customer['id'])
KeyError: 'id'

